name: "Populated topbar e2e test"
description: "Run an acceptance e2e test to ensure that populated topbar is working correctly in the hosted application"
inputs:
  application_url:
    description: The application url
    required: true
  username:
    description: Username for the user
    required: true
  password:
    description: Password for the user
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
        repository: "hadi-ansari161/populated-topbar-actions"
    - name: Install deps
      shell: bash
      run: |
        yarn
        yarn playwright install
    - uses: ./test.yml
      shell: bash
      with:
        username: ${{ secrets.E2E_USER }}
    - name: Set GitHub action path
      shell: bash
      run: E2E_USER=${{ inputs.username }} E2E_PASSWORD=${{ inputs.password }} APP_URL="${{ inputs.application_url }}" yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 10
